services:
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reviewApp
      TZ: UTC
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
